<?php

namespace Tests\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class CategoryControllerTest extends WebTestCase
{
    private $client;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->client = static::createClient();
    }

    /** @test */
    public function it_returns_the_categories()
    {
        // how to create factories that generate entities to test the response ???????

        $crawler = $this->client->request('GET', '/api/categories');

        $this->assertEquals(200, $this->client->getResponse()->getStatusCode());
    }
}
