api:
    prefix:   '/api/'
    resource: "@ApiBundle/Resources/config/routing.yml"

app:
    prefix: '/{any}'
    resource: '@AppBundle/Controller/'
    type:     annotation
    requirements:
        any: .*
